### ISSUE TITLE
Missed keypresses in plugin UI

### ISSUE THREAD

**Issue by peastman** [robbert-vdh/nih-plug#191]
I'm implementing the UI for my plugin with egui and testing it in Reaper on macOS.  It includes a text field for the user to type into.  It doesn't work correctly.  When I try to type into it, Reaper intercepts the keystrokes and interprets them as commands instead of sending them to the text field.

I found reports of the same problem in other VSTs:

https://forums.steinberg.net/t/how-receive-computer-keyboard-keystrokes-in-vst3-plugins/700967

https://github.com/iPlug2/iPlug2/issues/477

Based on those reports, I believe the problem is that NIH-plug doesn't implement `on_key_down()` and `on_key_up()`:

https://github.com/robbert-vdh/nih-plug/blob/16c6c58f4d9f08c9c515c991c218bff235cff6e2/src/wrapper/vst3/view.rs#L339-L355

Returning `kNotImplemented` tells the host that the plugin isn't interested in keypresses, and the host should interpret them itself.

The CLAP version of the plugin has the same problem.  I assume it has a similar mechanism.

**Comment by peastman** [comment]
For anyone coming across this issue, the real problem is in baseview.  https://github.com/RustAudio/baseview/issues/202 has a fix for it.  If anyone knows the developer of baseview and can encourage them to merge the fix (it's been two weeks with no response), that would be a big help!

**Comment by peastman** [comment]
Since no one has replied, I created a fork of egui-baseview with [a workaround](https://github.com/peastman/egui-baseview/commit/6dad67010f4157c1321b25f0a70abd2c6d0e13a4) for the problem.  Then I created a fork of NIH-Plug that [uses the fixed version](https://github.com/peastman/nih-plug/commit/980290b3b91696d9038f2d9ba463128a8657c21c).  This should fix the keyboard handling problems both in Reaper on Mac and in Ableton on Windows.  To use it, specify it in your Cargo.toml like this:

```toml
nih_plug = { git = "https://github.com/peastman/nih-plug.git", rev = "980290b3b91696d9038f2d9ba463128a8657c21c" }
nih_plug_egui = { git = "https://github.com/peastman/nih-plug.git", rev = "980290b3b91696d9038f2d9ba463128a8657c21c" }
```

Hopefully these fixes will eventually get adopted upstream, and the forks won't be needed anymore.
